services:
  pi-stats:
    build: .
    container_name: pi-stats
    hostname: pi-stats
    restart: unless-stopped
    volumes:
      - /usr/bin/vcgencmd:/usr/bin/vcgencmd
    privileged: true
    network_mode: host